name: pre-commit

on:
  pull_request:
  push:
    branches: [main]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Configurar Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Cambiar según la versión que uses
          cache: 'npm'

      # Instalar dependencias de Node.js
      - name: Install Dependencies
        run: npm install

      # Validar Conventional Commits
      - name: Check Conventional Commits
        uses: wagoid/commitlint-github-action@v5

      # Ejecutar Linter (ESLint)
      - name: Run ESLint
        run: npm run lint

      # Configurar Python (necesario para pre-commit)
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      # Ejecutar pre-commit hooks
      - name: Run pre-commit hooks
        uses: pre-commit/action@v3.0.1

      # Ejecutar Danger para validar PRs
      - name: Run Danger
        run: npx danger ci
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
